mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Root@123
    url: jdbc:mysql://localhost:3307/marketcenter?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    root: info
